<?php

namespace AppBundle\Repository;

/**
 * AccessprofileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessprofileRepository extends \Doctrine\ORM\EntityRepository
{
}
