<?php

namespace AppBundle\Repository;

/**
 * BillingclassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingclassRepository extends \Doctrine\ORM\EntityRepository
{
}
