<?php

namespace AppBundle\Repository;

/**
 * UserEquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEquipmentRepository extends \Doctrine\ORM\EntityRepository
{
}
